"""Type stubs for the `secretsweeper._native` CPython extension (src/python.zig)."""

import typing

# An opaque PyCapsule wrapping the automaton; only valid until `destroy`.
_Automaton: typing.TypeAlias = object

def new(patterns: typing.Iterable[bytes], use_dfa: bool) -> _Automaton: ...
def mask(automaton: _Automaton, data: bytes | bytearray | memoryview, limit: int, is_streaming: bool) -> bytes: ...
def get_reminder(automaton: _Automaton) -> bytes: ...
def reset_reminder(automaton: _Automaton) -> None: ...
def destroy(automaton: _Automaton) -> None: ...
